config/routes.rb
Rails.application.routes.draw do

  root   'home#index'
  get    'edit'    => 'home#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'projects/new/:id'  => 'projects#new_one'
  get   'signup'  => 'registration#signup'
  resources :profiles , only: [:new, :create, :update, :show]
  resources :educations , only: [:new]
  resources :experiences , only: [:new, :create, :update]
  resources :projects , only: [:new, :create, :update, :new_one]
  resources :users , only: [:new, :create, :show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    logged_in_user
    @user = current_user
  end

  def edit
    logged_in_user
    if current_user
        @profile = current_user.profile
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper

    def concat_str_with_comma(*array_of_str)
        if array_of_str.nil? or array_of_str.length == 0
            return ""
        end
        sanitized_array = array_of_str.compact.split("").flatten # removes nil and ""
        sanitized_array.join(',')
    end

    def get_array_from_comma_separated_string(str)
        str.strip.split(',')
    end
end

app/views/home/edit.html.erb
<%= render 'shared/header' %>

<main class="py-10 max-w-7xl mx-auto px-4 sm:px-8">
    <%= form_for(@profile, builder: TailwindInputBuilder) do |f| %>
        <div class="flex justify-end items-center w-full mb-4">
            <div>
                <%= render 'shared/input/buttons/copy_link', label: "Copy URL", href: " ", link: profile_url(@profile), color: "purple", onclick: "doThis()" %>
                <%= render 'shared/input/buttons/primary', label: "Preview", href: profile_path(@profile), color: "purple", method: nil %>
                <%= f.submit "Save", class: "flex-shrink-0 px-4 py-2 text-base font-semibold text-white bg-green-600 rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 focus:ring-offset-green-200" %><br/>
            </div>
        </div>

        <%= render 'shared/edit_section', title: "Profile details" do %>
            <%= f.text_field :name, value: @profile.name || current_user.name, placeholder: "Name" %><br/>
            <div class="flex items-center my-4">
                <% if @profile.image.attached? %>
                    <%= image_tag (url_for(@profile.image)), 
                        id: "image-preview", class: "shadow-xl rounded-full", style: "max-width:200px"
                    %>
                    <% else %>
                    <%= image_tag gravatar_url_for(current_user), 
                        id: "image-preview", style:"max-width:200px", 
                        class: "shadow-xl rounded-full" 
                    %>
                <% end %>
            </div>
            
            <%= f.label "Upload a profile image" %><br/>
            <%= f.file_field :image, accept: 'image/png, image/gif, image/jpeg' %><br/>

            <%= f.text_field :job_title, value: @profile.job_title, placeholder: "Job title" %><br/>
            <%= f.text_field :total_experience, value: @profile.total_experience, placeholder: "Total experience" %><br/>
            <%= f.text_area :overview, value: @profile.overview, placeholder: "Profile overview", required: true %><br/>
            <p>Career Highlights</p>
            <%= f.text_field :career_highlights, value: concat_str_with_comma(@profile.career_highlights), placeholder: "Career highlights" %>
            <%= render 'shared/multiple_inputs_message' %>
            
            <p>Primary Skills</p>
            <%= f.text_field :primary_skills, value: concat_str_with_comma(@profile.primary_skills), placeholder: "Primary skills" %>
            <%= render 'shared/multiple_inputs_message' %>
            
            <p>Secondary Skills</p>
            <%= f.text_field :secondary_skills, value: concat_str_with_comma(@profile.secondary_skills), placeholder: "Secondary skills" %>
            <%= render 'shared/multiple_inputs_message' %>
            
        <% end %>

        <%= render 'shared/edit_section', title: "Education" do %>
            <%= f.fields_for :educations do |education| %>
                <%= render 'shared/input/education', education: education %>
            <% end %><br />
            <%= render 'shared/input/buttons/add', label: "+ Add Education", path: "/educations/new" %>
        <% end %>

        <%= render 'shared/edit_section', title: "Experience" do %>
            <%= f.fields_for :experiences do |experience| %>
                <%= render 'shared/input/experience', experience: experience %>
                    <%= render 'shared/edit_section', title: "Project" do %>
                        <%= experience.fields_for :projects do |project| %>
                            <%= render 'shared/input/project', project: project %>
                        <% end %><br />
                        <% new_path = "/projects/new/" + (experience.object.id).to_s %>
                        <%= render 'shared/input/buttons/add', label: "+ Add Project", path: new_path %>
                    <% end %>

            <% end %><br />
            <%= render 'shared/input/buttons/add', label: "+ Add Experience", path: "/experiences/new" %>
        <% end %>
        
    <% end %>

</main>

app/views/home/index.html.erb
<%= render 'shared/header' %>

<main class="py-10 max-w-7xl mx-auto px-4 sm:px-8">
  
    <div class="flex justify-between align-center">
    
        <h1 class="text-3xl"> 
            Welcome, <span class="text-purple-600 font-semibold"><%= @user.name %><span>
        </h1>
        <%= render 'shared/input/buttons/secondary', color: "purple", label: "Edit", href: edit_url %>
    </div>
    
    <%= render 'shared/profile/preview', profile: @user.profile %>
</main>